name: Python CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint flake8 black mypy
      - name: Lint with pylint
        run: |
          pylint **/*.py
      - name: Check code format with black
        run: |
          black --check .
      - name: Lint with flake8
        run: |
          flake8 .
      - name: Type check with mypy
        run: |
          mypy **/*.py

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests
        run: |
          pytest

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.9'
      - name: Install black
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Format code with black
        run: |
          black .
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Format code with black" || echo "No changes to commit"
          git push
